### ISSUE TITLE
Make use of new select-entity

### ISSUE THREAD

**Issue by danielperna84** [SukramJ/aiohomematic#11]
The latest Home Assistant release has introduced the [select](https://www.home-assistant.io/integrations/select/) entity. This would be a better choice than using `input_select`.

**Comment by SukramJ** [comment]
I don't think `input_*` should be created programmatically. It's an integration and not an entity platform,
`input_select` could easily refactored to a `select` entity, but there is no corresponding entity platform for `input_text`.
Which device has a text parameter, that should be changed without an existing value list?

**Comment by danielperna84** [comment]
You're right about the `select`, hence, this issue. I have included the `input_text` more or less as a placeholder because, as you have noticed, there's no platform for this. Anyways, [here](https://github.com/danielperna84/hahomematic/blob/48cce95a8d6dc7870dfbb236935f83b4a5c7c012/hahomematic/device.py#L237) I'm referencing parameters which are of the type `STRING`. As you can see [here](https://github.com/danielperna84/pydevccu/search?q=STRING), there aren't many of those. And in such cases I guess it would be ok to fall back to doing it manually via a `homemativ.set_value` service.

Fell free to remove the `input_text`. 👍 Although I actually think it would be nice if HA supported entering arbitrary text. But that's out of scope for now.

**Comment by SukramJ** [comment]
Done
