### ISSUE TITLE
Provide async implementation

### ISSUE THREAD

**Issue by danielperna84** [SukramJ/aiohomematic#4]
As mentioned [here](https://github.com/danielperna84/hahomematic/issues/1#issuecomment-816060710), async versions of XML-RPC modules have emerged. Maybe we can support that with `hahomematic`. But it has to be thoroughly tested. We had [problems with parallelism](https://github.com/danielperna84/pyhomematic/issues/13) in the past.

**Comment by itn3rd77** [comment]
This issue can be closed as pull request #27 was merged, right?

**Comment by SukramJ** [comment]
Done
