### ISSUE TITLE
HMIPServer sends all devices to newDevices even though they appeared in listDevices

### ISSUE THREAD

**Issue by danielperna84** [SukramJ/aiohomematic#7]
During `init` the CCU asks our server about present devices by calling `listDevices`. We correctly respond with a list of devices - by this time we already have created the entities from cache - but the CCU still sends a list of __all__ devices again, causing the server to create the entities once more. This might be a bug in HMIPServer.

**Comment by danielperna84** [comment]
Workaround implemented. This will require entities to be removed from `hahomematic.data.ENTITIES` in case they should be updated during runtime.

**Comment by SukramJ** [comment]
There is already code implemented to cleanup collections on deleteDevices.
Entities, Devices, EventSubscriptions, Caches and more.
The device will also be removed from HA.
Is this ticket still needed?

**Comment by danielperna84** [comment]
I think it can be closed. The main problem I had back then was, that HmIP devices (entities) were created twice - first from cache, then again when the CCU sends the list be calling the `newDevices` method on our RPC-endpoint. If you don't get duplicate entities now, then this shouldn't be an issue anymore.
