### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by danielperna84** [SukramJ/aiohomematic#9]
Obviously it would make sense to add tests. My other project [pydevccu](https://github.com/danielperna84/pydevccu) could be used as the backend (virtual CCU) to ensure everybody can run the tests.

Since the project is still in a early phase it might make sense to wait a bit until we reach a state where less changes will happen.

**Comment by danielperna84** [comment]
@SukramJ 

Ich habe eben Version [0.1.0](https://github.com/danielperna84/pydevccu/releases/tag/0.1.0) von pydevccu veröffentlicht. Da sind nun die ganzen neuen Geräte (auch deine die ich eben gemerged habe) mit drin. Ändert praktisch zwar nix, aber jetzt weißt du bescheid. 👍

**Comment by SukramJ** [comment]
Danke

**Comment by SukramJ** [comment]
Hi @danielperna84,
pydevccu ist in der Entwicklung und Geräteintegration sehr nützlich, und so kann man HA euch mal mit einem anderen Gerätebestand testen.
Speziell Cover und Climate sind bei Implementierung und Test aufwendiger, und hierzu gab es bisher die meisten Issues.
Hier würde ich mir wünschen, wenn einzelne Geräte etwas mehr Logik bekommen könnten. Insbesondere Fälle wo man in Wert A schreibt, die Ergebnisse aber aus Wert B auslesen muss, sind interessant. 

Kannst Du dir dazu ein Implementierung vorstellen, oder ist das zu aufwendig?

**Comment by danielperna84** [comment]
Grundsätzlich ist das schon möglich. Bisher habe ich da ja nur zwei Sensoren drin. _Einfache_ Aktoren lassen sich ja jetzt prinzipiell schon steuern. Es wird halt einfach direkt der Wert ins Paramset geschrieben, was bei Schalt-Aktoren halbwegs akkurat sein sollte. Hier fehlen dann nur die _Problemfälle_ mit den virtuellen Kanälen. Da muss ich mal schauen wie ich da Callbacks einbaue, damit der Statuskanal dann auch entsprechend aktualisiert wird. Ich denke mal aber, dass es für Testzwecke reichen sollte nur den ersten Steuerkanal mit dem Statuskanal zu synchronisieren. Die Logik der virtuellen Kanäle nachzubilden wäre wohl etwas übertrieben.

Ich habe noch einen verpackten HmIP-FROLL rumliegen der im Frühling in Betrieb genommen werden soll. Da hab ich dann auch eine Referenz für einen Rolladen-Aktor. 👍

**Comment by danielperna84** [comment]
Ich habe nun [0.1.1](https://github.com/danielperna84/pydevccu/releases/tag/0.1.1) veröffentlicht. Ist der aktuellste Stand, inklusive dem Fix für HmIP-DLD. 👍

**Comment by SukramJ** [comment]
Ongoing
